twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
      brand_name: 'Le monde du chocolat'

when@test:
    twig:
        strict_variables: true
